### ISSUE TITLE
Implement validation and error messages

### ISSUE THREAD

**Issue by LionOps** [yola/ampersand-multifield-view#7]
We're going to want to be able to have validation on the relationship of a multifield view's input and a mechanism to display error messages.

As an example, when implementing opening and closing hours, if opening hours are given, we should require closing hours and vice versa.

The validation should mimic other field views:

> - Will not show error messages pre-submit, or if it's never had a valid value. This lets people tab-through a form without triggering a bunch of error messages.
> - Live-validates, to always report if in valid state. But only shows messages when sane to do so.
> - Only shows first failed message. Then, as the user corrects, updates and validates against all tests, showing appropriate message, until all tests pass.

**Comment by snitch** [comment]
@DevShep: This issue is now a priority.
